-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


welcome : Translations -> String -> String
welcome translations name =
    tr translations Curly "welcome" [ ( "name", name ) ]


logout : Translations -> String
logout translations =
    t translations "logout"
